name: 'Datadog Upload dSYMs'
description: 'Upload dSYM files to Datadog to symbolicate your crash reports.'
author: 'Datadog'
branding:
  icon: upload
  color: purple
inputs:
  api_key:
    required: true
    description: 'Datadog API key.'
  site:
    required: false
    description: 'Datadog site region. `datadoghq.com` by default, use `datadoghq.eu` for the EU.'
    default: 'datadoghq.com'
  dsym_paths: 
    required: true
    description: 'Path to dSYM files. Supports folder and/or zip files.'
  dry_run: 
    required: false
    description: 'If true, it will run the command without the final step of upload. All other checks are performed.'
runs:
  using: 'node20'
  main: 'dist/index.js'
