name: 'Datadog Upload dSYMs'
description: 'Upload dSYM files to Datadog to symbolicate your crash reports.'
author: 'Datadog'
inputs:
  api_key:
    required: true
    description: 'Datadog API key.'
  dsym_paths: 
    required: true
    description: 'Path to dSYM files. Support folder and/or zip files'
  dry_run: 
    required: false
    description: 'If true, it will run the command without the final step of upload. All other checks are performed.'
runs:
  using: 'node12'
  main: 'dist/index.js'
